package com.hermes.android.core.design.tokens

import androidx.compose.ui.graphics.Color

object HermesColorTokens {
    object Dark {
        val accent = Color(#7C5CFF)
        val accentSoft = Color(#2A2350)
        val accentOn = Color(#FFFFFF)
        val success = Color(#3DDC84)
        val warning = Color(#FFB020)
        val danger = Color(#FF5C5C)
        val info = Color(#5AC8FA)
        val statusIdle = Color(#8A8A99)
        val statusRunning = Color(#7C5CFF)
        val statusAwaiting = Color(#FFB020)
        val statusDone = Color(#3DDC84)
        val statusStopped = Color(#8A8A99)
        val statusError = Color(#FF5C5C)
        val roleUser = Color(#7C5CFF)
        val roleAssistant = Color(#FFFFFF)
        val roleTool = Color(#5AC8FA)
        val roleSystem = Color(#8A8A99)
        val background = Color(#0B0B10)
        val surface = Color(#16161E)
        val surfaceVariant = Color(#1F1F2A)
        val surfaceRaised = Color(#242433)
        val border = Color(#2E2E3C)
        val onSurface = Color(#FFFFFF)
        val onSurfaceMuted = Color(#8A8A99)
        val onSurfaceSubtle = Color(#6A6A78)
    }
    object Light {
        val accent = Color(#7C5CFF)
        val accentSoft = Color(#2A2350)
        val accentOn = Color(#FFFFFF)
        val success = Color(#3DDC84)
        val warning = Color(#FFB020)
        val danger = Color(#FF5C5C)
        val info = Color(#5AC8FA)
        val statusIdle = Color(#8A8A99)
        val statusRunning = Color(#7C5CFF)
        val statusAwaiting = Color(#FFB020)
        val statusDone = Color(#3DDC84)
        val statusStopped = Color(#8A8A99)
        val statusError = Color(#FF5C5C)
        val roleUser = Color(#7C5CFF)
        val roleAssistant = Color(#0B0B10)
        val roleTool = Color(#5AC8FA)
        val roleSystem = Color(#8A8A99)
        val background = Color(#F7F7FB)
        val surface = Color(#FFFFFF)
        val surfaceVariant = Color(#F0F0F6)
        val surfaceRaised = Color(#E9E9F2)
        val border = Color(#DCDCE6)
        val onSurface = Color(#16161E)
        val onSurfaceMuted = Color(#5A5A68)
        val onSurfaceSubtle = Color(#8A8A99)
    }
}
