package com.hermes.android.core.design.tokens

import androidx.compose.ui.graphics.Color

object HermesColorTokens {
    object Dark {
        val accent = Color(0xFF7C5CFF)
        val accentSoft = Color(0xFF2A2350)
        val accentOn = Color(0xFFFFFFFF)
        val success = Color(0xFF3DDC84)
        val warning = Color(0xFFFFB020)
        val danger = Color(0xFFFF5C5C)
        val info = Color(0xFF5AC8FA)
        val statusIdle = Color(0xFF8A8A99)
        val statusRunning = Color(0xFF7C5CFF)
        val statusAwaiting = Color(0xFFFFB020)
        val statusDone = Color(0xFF3DDC84)
        val statusStopped = Color(0xFF8A8A99)
        val statusError = Color(0xFFFF5C5C)
        val roleUser = Color(0xFF7C5CFF)
        val roleAssistant = Color(0xFFFFFFFF)
        val roleTool = Color(0xFF5AC8FA)
        val roleSystem = Color(0xFF8A8A99)
        val background = Color(0xFF0B0B10)
        val surface = Color(0xFF16161E)
        val surfaceVariant = Color(0xFF1F1F2A)
        val surfaceRaised = Color(0xFF242433)
        val border = Color(0xFF2E2E3C)
        val onSurface = Color(0xFFFFFFFF)
        val onSurfaceMuted = Color(0xFF8A8A99)
        val onSurfaceSubtle = Color(0xFF6A6A78)
    }
    object Light {
        val accent = Color(0xFF7C5CFF)
        val accentSoft = Color(0xFF2A2350)
        val accentOn = Color(0xFFFFFFFF)
        val success = Color(0xFF3DDC84)
        val warning = Color(0xFFFFB020)
        val danger = Color(0xFFFF5C5C)
        val info = Color(0xFF5AC8FA)
        val statusIdle = Color(0xFF8A8A99)
        val statusRunning = Color(0xFF7C5CFF)
        val statusAwaiting = Color(0xFFFFB020)
        val statusDone = Color(0xFF3DDC84)
        val statusStopped = Color(0xFF8A8A99)
        val statusError = Color(0xFFFF5C5C)
        val roleUser = Color(0xFF7C5CFF)
        val roleAssistant = Color(0xFF0B0B10)
        val roleTool = Color(0xFF5AC8FA)
        val roleSystem = Color(0xFF8A8A99)
        val background = Color(0xFFF7F7FB)
        val surface = Color(0xFFFFFFFF)
        val surfaceVariant = Color(0xFFF0F0F6)
        val surfaceRaised = Color(0xFFE9E9F2)
        val border = Color(0xFFDCDCE6)
        val onSurface = Color(0xFF16161E)
        val onSurfaceMuted = Color(0xFF5A5A68)
        val onSurfaceSubtle = Color(0xFF8A8A99)
    }
}
